# Generated by Django 4.1.2 on 2022-10-20 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('title', 'nickname')},
        ),
    ]
